CREATE TABLE tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    due_date DATE DEFAULT NULL,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    assigned_to INTEGER REFERENCES users(id) ON DELETE SET NULL,
    date_completed TIMESTAMP DEFAULT NULL
);